// Custom variables
#define LIL_CUSTOM_PROPERTIES \
float _DecalCount; \
float4 _Decal1Color; \
float4 _Decal1Tex_ST; \
float _Decal1TexAngle; \
lilBool _Decal1ShouldCopy; \
lilBool _Decal1ShouldFlipCopy; \
uint _Decal1BlendMode; \
uint _Decal1Tex_UVMode; \
float4 _Decal2Color; \
float4 _Decal2Tex_ST; \
float _Decal2TexAngle; \
lilBool _Decal2ShouldCopy; \
lilBool _Decal2ShouldFlipCopy; \
uint _Decal2BlendMode; \
uint _Decal2Tex_UVMode; \
float4 _Decal3Color; \
float4 _Decal3Tex_ST; \
float _Decal3TexAngle; \
lilBool _Decal3ShouldCopy; \
lilBool _Decal3ShouldFlipCopy; \
uint _Decal3BlendMode; \
uint _Decal3Tex_UVMode; \
float4 _Decal4Color; \
float4 _Decal4Tex_ST; \
float _Decal4TexAngle; \
lilBool _Decal4ShouldCopy; \
lilBool _Decal4ShouldFlipCopy; \
uint _Decal4BlendMode; \
uint _Decal4Tex_UVMode; \
float4 _Decal5Color; \
float4 _Decal5Tex_ST; \
float _Decal5TexAngle; \
lilBool _Decal5ShouldCopy; \
lilBool _Decal5ShouldFlipCopy; \
uint _Decal5BlendMode; \
uint _Decal5Tex_UVMode; \
float4 _Decal6Color; \
float4 _Decal6Tex_ST; \
float _Decal6TexAngle; \
lilBool _Decal6ShouldCopy; \
lilBool _Decal6ShouldFlipCopy; \
uint _Decal6BlendMode; \
uint _Decal6Tex_UVMode; \
float4 _Decal7Color; \
float4 _Decal7Tex_ST; \
float _Decal7TexAngle; \
lilBool _Decal7ShouldCopy; \
lilBool _Decal7ShouldFlipCopy; \
uint _Decal7BlendMode; \
uint _Decal7Tex_UVMode; \
float4 _Decal8Color; \
float4 _Decal8Tex_ST; \
float _Decal8TexAngle; \
lilBool _Decal8ShouldCopy; \
lilBool _Decal8ShouldFlipCopy; \
uint _Decal8BlendMode; \
uint _Decal8Tex_UVMode; \
float4 _Decal9Color; \
float4 _Decal9Tex_ST; \
float _Decal9TexAngle; \
lilBool _Decal9ShouldCopy; \
lilBool _Decal9ShouldFlipCopy; \
uint _Decal9BlendMode; \
uint _Decal9Tex_UVMode; \
float4 _Decal10Color; \
float4 _Decal10Tex_ST; \
float _Decal10TexAngle; \
lilBool _Decal10ShouldCopy; \
lilBool _Decal10ShouldFlipCopy; \
uint _Decal10BlendMode; \
uint _Decal10Tex_UVMode; \
lilBool _Decal1TexIsMSDF; \
lilBool _Decal2TexIsMSDF; \
lilBool _Decal3TexIsMSDF; \
lilBool _Decal4TexIsMSDF; \
lilBool _Decal5TexIsMSDF; \
lilBool _Decal6TexIsMSDF; \
lilBool _Decal7TexIsMSDF; \
lilBool _Decal8TexIsMSDF; \
lilBool _Decal9TexIsMSDF; \
lilBool _Decal10TexIsMSDF; \
lilBool _Decal1UseAnimation; \
lilBool _Decal2UseAnimation; \
lilBool _Decal3UseAnimation; \
lilBool _Decal4UseAnimation; \
lilBool _Decal5UseAnimation; \
lilBool _Decal6UseAnimation; \
lilBool _Decal7UseAnimation; \
lilBool _Decal8UseAnimation; \
lilBool _Decal9UseAnimation; \
lilBool _Decal10UseAnimation; \
float4 _Decal1TexDecalAnimation; \
float4 _Decal2TexDecalAnimation; \
float4 _Decal3TexDecalAnimation; \
float4 _Decal4TexDecalAnimation; \
float4 _Decal5TexDecalAnimation; \
float4 _Decal6TexDecalAnimation; \
float4 _Decal7TexDecalAnimation; \
float4 _Decal8TexDecalAnimation; \
float4 _Decal9TexDecalAnimation; \
float4 _Decal10TexDecalAnimation; \
float _AudioLinkDecal1ScaleBand; \
float4 _AudioLinkDecal1Scale; \
float _AudioLinkDecal2ScaleBand; \
float4 _AudioLinkDecal2Scale; \
float _AudioLinkDecal3ScaleBand; \
float4 _AudioLinkDecal3Scale; \
float _AudioLinkDecal4ScaleBand; \
float4 _AudioLinkDecal4Scale; \
float _AudioLinkDecal5ScaleBand; \
float4 _AudioLinkDecal5Scale; \
float _AudioLinkDecal6ScaleBand; \
float4 _AudioLinkDecal6Scale; \
float _AudioLinkDecal7ScaleBand; \
float4 _AudioLinkDecal7Scale; \
float _AudioLinkDecal8ScaleBand; \
float4 _AudioLinkDecal8Scale; \
float _AudioLinkDecal9ScaleBand; \
float4 _AudioLinkDecal9Scale; \
float _AudioLinkDecal10ScaleBand; \
float4 _AudioLinkDecal10Scale; \
float _AudioLinkDecal1AnimationBand; \
float _AudioLinkDecal2AnimationBand; \
float _AudioLinkDecal3AnimationBand; \
float _AudioLinkDecal4AnimationBand; \
float _AudioLinkDecal5AnimationBand; \
float _AudioLinkDecal6AnimationBand; \
float _AudioLinkDecal7AnimationBand; \
float _AudioLinkDecal8AnimationBand; \
float _AudioLinkDecal9AnimationBand; \
float _AudioLinkDecal10AnimationBand; \
float _AudioLinkDecal1AnimationUse; \
float _AudioLinkDecal2AnimationUse; \
float _AudioLinkDecal3AnimationUse; \
float _AudioLinkDecal4AnimationUse; \
float _AudioLinkDecal5AnimationUse; \
float _AudioLinkDecal6AnimationUse; \
float _AudioLinkDecal7AnimationUse; \
float _AudioLinkDecal8AnimationUse; \
float _AudioLinkDecal9AnimationUse; \
float _AudioLinkDecal10AnimationUse; \
float _AudioLinkDecal1AnimationStart; \
float _AudioLinkDecal2AnimationStart; \
float _AudioLinkDecal3AnimationStart; \
float _AudioLinkDecal4AnimationStart; \
float _AudioLinkDecal5AnimationStart; \
float _AudioLinkDecal6AnimationStart; \
float _AudioLinkDecal7AnimationStart; \
float _AudioLinkDecal8AnimationStart; \
float _AudioLinkDecal9AnimationStart; \
float _AudioLinkDecal10AnimationStart; \
float _AudioLinkDecal1SideBand; \
float4 _AudioLinkDecal1SideMonMin; \
float4 _AudioLinkDecal1SideMonMax; \
float _AudioLinkDecal2SideBand; \
float4 _AudioLinkDecal2SideMonMin; \
float4 _AudioLinkDecal2SideMonMax; \
float _AudioLinkDecal3SideBand; \
float4 _AudioLinkDecal3SideMonMin; \
float4 _AudioLinkDecal3SideMonMax; \
float _AudioLinkDecal4SideBand; \
float4 _AudioLinkDecal4SideMonMin; \
float4 _AudioLinkDecal4SideMonMax; \
float _AudioLinkDecal5SideBand; \
float4 _AudioLinkDecal5SideMonMin; \
float4 _AudioLinkDecal5SideMonMax; \
float _AudioLinkDecal6SideBand; \
float4 _AudioLinkDecal6SideMonMin; \
float4 _AudioLinkDecal6SideMonMax; \
float _AudioLinkDecal7SideBand; \
float4 _AudioLinkDecal7SideMonMin; \
float4 _AudioLinkDecal7SideMonMax; \
float _AudioLinkDecal8SideBand; \
float4 _AudioLinkDecal8SideMonMin; \
float4 _AudioLinkDecal8SideMonMax; \
float _AudioLinkDecal9SideBand; \
float4 _AudioLinkDecal9SideMonMin; \
float4 _AudioLinkDecal9SideMonMax; \
float _AudioLinkDecal10SideBand; \
float4 _AudioLinkDecal10SideMonMin; \
float4 _AudioLinkDecal10SideMonMax; \
float _AudioLinkDecal1RotationBand; \
float2 _AudioLinkDecal1Rotation; \
float _AudioLinkDecal2RotationBand; \
float2 _AudioLinkDecal2Rotation; \
float _AudioLinkDecal3RotationBand; \
float2 _AudioLinkDecal3Rotation; \
float _AudioLinkDecal4RotationBand; \
float2 _AudioLinkDecal4Rotation; \
float _AudioLinkDecal5RotationBand; \
float2 _AudioLinkDecal5Rotation; \
float _AudioLinkDecal6RotationBand; \
float2 _AudioLinkDecal6Rotation; \
float _AudioLinkDecal7RotationBand; \
float2 _AudioLinkDecal7Rotation; \
float _AudioLinkDecal8RotationBand; \
float2 _AudioLinkDecal8Rotation; \
float _AudioLinkDecal9RotationBand; \
float2 _AudioLinkDecal9Rotation; \
float _AudioLinkDecal10RotationBand; \
float2 _AudioLinkDecal10Rotation; \
float _AudioLinkDecal1ChronoRotationBand; \
float _AudioLinkDecal1ChronoMotionType; \
float _AudioLinkDecal1ChronoRotationSpeed; \
float _AudioLinkDecal2ChronoRotationBand; \
float _AudioLinkDecal2ChronoMotionType; \
float _AudioLinkDecal2ChronoRotationSpeed; \
float _AudioLinkDecal3ChronoRotationBand; \
float _AudioLinkDecal3ChronoMotionType; \
float _AudioLinkDecal3ChronoRotationSpeed; \
float _AudioLinkDecal4ChronoRotationBand; \
float _AudioLinkDecal4ChronoMotionType; \
float _AudioLinkDecal4ChronoRotationSpeed; \
float _AudioLinkDecal5ChronoRotationBand; \
float _AudioLinkDecal5ChronoMotionType; \
float _AudioLinkDecal5ChronoRotationSpeed; \
float _AudioLinkDecal6ChronoRotationBand; \
float _AudioLinkDecal6ChronoMotionType; \
float _AudioLinkDecal6ChronoRotationSpeed; \
float _AudioLinkDecal7ChronoRotationBand; \
float _AudioLinkDecal7ChronoMotionType; \
float _AudioLinkDecal7ChronoRotationSpeed; \
float _AudioLinkDecal8ChronoRotationBand; \
float _AudioLinkDecal8ChronoMotionType; \
float _AudioLinkDecal8ChronoRotationSpeed; \
float _AudioLinkDecal9ChronoRotationBand; \
float _AudioLinkDecal9ChronoMotionType; \
float _AudioLinkDecal9ChronoRotationSpeed; \
float _AudioLinkDecal10ChronoRotationBand; \
float _AudioLinkDecal10ChronoMotionType; \
float _AudioLinkDecal10ChronoRotationSpeed;
\
float _MoreDecal_AnimBandThreshold; \
float _MoreDecal_AnimBandGain; \
float _MoreDecal_AnimBandGamma; \

#if defined(LIL_FEATURE_AUDIOLINK) && !defined(AUDIOLINK_CGINC_INCLUDED)
TEXTURE2D_FLOAT(_AudioTexture);
float4 _AudioTexture_TexelSize;
#endif

#define LIL_CUSTOM_TEXTURES \
TEXTURE2D(_Decal1Tex); \
TEXTURE2D(_Decal2Tex); \
TEXTURE2D(_Decal3Tex); \
TEXTURE2D(_Decal4Tex); \
TEXTURE2D(_Decal5Tex); \
TEXTURE2D(_Decal6Tex); \
TEXTURE2D(_Decal7Tex); \
TEXTURE2D(_Decal8Tex); \
TEXTURE2D(_Decal9Tex); \
TEXTURE2D(_Decal10Tex);

#ifndef sampler_DecalTex
#define sampler_DecalTex sampler_linear_repeat
#endif